image: ubuntu-18.04-amd64
environment:
  DEPLOYMENT_HOST: ssh://psituser@swm.damutten.ch
  JDK_VERSION: adoptopenjdk-8-hotspot-amd64
install:
  - sudo java_select $JDK_VERSION
  - sudo apt-get update && sudo apt install curl
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
stack: jdk 8
build_script:
  - ./mvnw clean install package -B
artifacts:
  - path: "target/*.jar"
on_finish:
  # Search the 'target' folder for all JUnit test reports and upload them to the CI server.
  - sh: |
      find "$APPVEYOR_BUILD_FOLDER/target" -type f -name 'TEST*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.cloudlab.zhaw.ch/api/testresults/junit/$APPVEYOR_JOB_ID"
# We do not want to build git tags.
skip_tags: true
deploy_script:
  #- sh: ssh psituser@swm.damutten.ch 'df -H'
  #- sh: export DOCKER_HOST=${DEPLOYMENT_HOST}
  - sh: docker-compose build
  - sh: docker-compose up --no-deps -d app
cache:
  - "$HOME/.cache"
  - "$HOME/.m2/repository"
  - "$HOME/.m2/wrapper"
  - "$HOME/.sonar/cache"
  - "/usr/local/bin/docker-compose"
version: '1.0.{build}'
