image: ubuntu-18.04-amd64
environment:
  DEPLOYMENT_HOST: ssh://psituser@swm.damutten.ch
  JDK_VERSION: adoptopenjdk-8-hotspot-amd64
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmvWJaol+5upE3YghLPn3bPIAOBmYTw5t8P+w/2QJnlLEaCqOZIC9+4w7wf7ec6j9c7Iae+3HvP2qsLERXnkkqTLr0wA0ua91A4hzuYk82Uxtnqgc5i9PswR0zDk1X40DCFZK/BT/sbCGwAD7jn9D1yrzgmC6UgomUninR4URUXJstELhL0LLKW1j/TYHVcQYooKCehSkFkf4i72RPuEMwNEpl1/QDmaWFXYLkMBVv/ZtF5DV7vZGL46oxOsEcWcgk7H5im5XSOb0byZes0ObSOmy4tu3gx8vhfijlrItkbWR2n4PrVBIXhOwT5A1RyGpJChKEeugVhcnruiPUVGkl OpenShift-Key
install:
  - sudo java_select $JDK_VERSION
  - sudo apt-get update && sudo apt install curl
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
stack: jdk 8
build_script:
  - ./mvnw clean install package -B
artifacts:
  - path: "target/*.jar"
on_finish:
  # Search the 'target' folder for all JUnit test reports and upload them to the CI server.
  - sh: |
      find "$APPVEYOR_BUILD_FOLDER/target" -type f -name 'TEST*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.cloudlab.zhaw.ch/api/testresults/junit/$APPVEYOR_JOB_ID"
# We do not want to build git tags.
skip_tags: true
deploy_script:
  - sh: docker context create remote --docker "host=$DEPLOYMENT_HOST"
  - sh: docker context use remote
  - sh: export APPVEYOR_SSH_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
  - sh: docker-compose -H "$DEPLOYMENT_HOST" up --build
cache:
  - "$HOME/.cache"
  - "$HOME/.m2/repository"
  - "$HOME/.m2/wrapper"
  - "$HOME/.sonar/cache"
version: '1.0.{build}'
