version: "3"
services:
  mongodb:
    image: mongo:4.2.3
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - "dbdata:/data/db"
  app:
    build:
      context: .
      args:
        - JAR_FILE=target/wall-0.0.1-SNAPSHOT.jar
    image: backend:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
volumes:
  dbdata:
