version: "3"
services:
  mongodb:
    image: mongo:4.2.3
    ports:
      - 27017:27017
    volumes:
      - "dbdata:/data/db"
  app:
    build:
      context: .
    image: backend:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
    tmpfs:
      - /tmp

volumes:
  dbdata:
