version: "3"
services:
  mongodb:
    image: mongo:4.2.3
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_DATABASE=swm
    volumes:
      - "dbdata:/data/db"
      - "./mongodb/init_data.js:/docker-entrypoint-initdb.d/init_data.js"
  app:
    build:
      context: .
    image: backend:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
    tmpfs:
      - /tmp

volumes:
  dbdata:
