POST http://localhost:8080/posts/comments
Content-Type: application/json

{
"topicId": "5ea6e6226f3dc315cf22eae1",
"personId": "10",
"message": "comment of person 10"
}

###

POST http://localhost:8080/posts/comments
Content-Type: application/json

{
"topicId": "5ea6e6226f3dc315cf22eae1",
"personId": "30",
"message": "another comment. this time of person 20"
}

###
