POST http://localhost:8080/relationships
Content-Type: application/json

{
    "requestingPersonId": "5eaf1991d26a08a2b5d9ff1d",
    "requestedPersonId": "5e9c6d85d5375d17ce33bd32"
}

###
POST http://localhost:8080/relationships
Content-Type: application/json

{
    "requestingPersonId": "5eaf1991d26a08a2b5d9ff1d",
    "requestedPersonId": "5eaf1991d26a08a2b5d9ff1d"
}

###
POST http://localhost:8080/relationships
Content-Type: application/json

{
    "requestingPersonId": "5e9c6d85d5375d17ce33bd32",
    "requestedPersonId": "5eaf154c32107b713fe0e2d7"
}

###
PATCH http://localhost:8080/relationships/5eaf19b7a8cc18d0534777eb
Content-Type: application/json

{
    "status": "ACCEPTED"
}

###
DELETE http://localhost:8080/relationships/5eaf19b7a8cc18d0534777eb
Accept: application/json

####
