POST http://localhost:8080/topics
Content-Type: application/json

{
    "title": "Topic 1",
    "personId": "123"
}

###
POST http://localhost:8080/topics
Content-Type: application/json

{
    "personId": "123"
}

###
POST http://localhost:8080/topics
Content-Type: application/json

{
    "title": "Topic 1",
    "personId": "5e81c779e08c5427d4acd4bb"
}

###
GET http://localhost:8080/topics
Accept: application/json

###
GET http://localhost:8080/topics/5e81b8070fcbbf47972ac63d
Accept: application/json

###

DELETE http://localhost:8080/topics/5e81b8070fcbbf47972ac63d
Accept: application/json

###
